openapi: 3.0.0
info:
    title: test-object client
    version: '1.0'

paths:
    /test1:
        x-tag: test
        post:
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                additionalProperties: false
                                properties: {}
components: {}
