default: {}
description: ''
schema:
    type: object
    example: |
        {
            // Настройки для конкретного компонента сервиса.
            "postgresql-grocery_orders": {
                "max_statement_metrics": 50
            }
        }
    additionalProperties:
        $ref: "#/definitions/StatementMetricsSettings"
    definitions:
        StatementMetricsSettings:
            type: object
            additionalProperties: false
            properties:
                max_statement_metrics:
                    type: integer
                    minimum: 0
