default: {}
description: ''
schema:
    type: object
    additionalProperties:
        $ref: "#/definitions/PoolSettings"
    definitions:
        PoolSettings:
            type: object
            additionalProperties: false
            properties:
                min_pool_size:
                    type: integer
                    minimum: 0
                max_pool_size:
                    type: integer
                    minimum: 1
                max_queue_size:
                    type: integer
                    minimum: 1
                connecting_limit:
                    type: integer
                    minimum: 0
            required:
              - min_pool_size
              - max_pool_size
              - max_queue_size
