# yaml
components_manager:
    components:
        handler-key-value:
            path: /basic/sqlite/key-value
            task_processor: main-task-processor
            method: GET,DELETE,POST,PUT

        handler-batch:
            path: /basic/sqlite/batch
            task_processor: main-task-processor
            method: GET,DELETE,POST

        testsuite-support:

        key-value-database:
            db-path: "/tmp/kv.db"
            task_processor: fs-task-processor

        batch-database:
            db-path: "/tmp/batch.db"
            task_processor: fs-task-processor

        server:
            listener:
                port: 8080
                task_processor: main-task-processor
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: "@stderr"
                    level: debug
                    overflow_behavior: discard

        dns-client:
            fs-task-processor: fs-task-processor

    task_processors:
        main-task-processor:
            worker_threads: 4
        fs-task-processor:
            worker_threads: 4

    default_task_processor: main-task-processor
