openapi: 3.0.0
info:
    title: test-object client
    version: '1.0'

paths:
    /test1:
        get:
            operationId: MyTest
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties: {}
                                additionalProperties: false
components: {}
