default: {}
description: |
    Dynamic config that controls the redis pubsub metric settings for specific service.

    Dictionary keys can be either the **database name** (not the component name!)
    or `__default__`. The latter configuration is applied for every non-matching
    Redis database/sentinel of the service.
schema:
    type: object
    additionalProperties: false
    example: |
        {
            "per-shard-stats-enabled": true,
        }
    properties:
        per-shard-stats-enabled:
            type: boolean
            default: true
