default: {}
description: |
    Dynamic config that controls the metric settings for specific service.

    Dictionary keys can be either the **database name** (not the component name!)
    or `__default__`. The latter configuration is applied for every non-matching
    Redis database/sentinel of the service.
schema:
    type: object
    additionalProperties: false
    example: |
        {
            "timings-enabled": true,
            "command-timings-enabled": true,
            "request-sizes-enabled": true,
            "reply-sizes-enabled": true
        }
    properties:
        timings-enabled:
            type: boolean
            default: true
        command-timings-enabled:
            type: boolean
            default: false
        request-sizes-enabled:
            type: boolean
            default: false
        reply-sizes-enabled:
            type: boolean
            default: false
