default:
    buffering_enabled: false
    watch_command_timer_interval_us: 0
description: |
    Dynamic config that controls command buffering for specific service.
    Enabling of this config activates a delay in sending commands. When commands are sent, they are combined into a single tcp packet and sent together.
    First command arms timer and then during `watch_command_timer_interval_us` commands are accumulated in the buffer

    Command buffering is disabled by default.
schema:
    example: |
        {
          "buffering_enabled": true,
          "commands_buffering_threshold": 10,
          "watch_command_timer_interval_us": 1000
        }
    type: object
    additionalProperties: false
    properties:
        buffering_enabled:
            type: boolean
        commands_buffering_threshold:
            type: integer
            minimum: 1
        watch_command_timer_interval_us:
            type: integer
            minimum: 0
    required:
      - buffering_enabled
      - watch_command_timer_interval_us
