default: {}
description: |
    Whether Congestion Control is enabled for specified MongoDB databases.
    Overrides settings from MONGO_CONGESTION_CONTROL_ENABLED.

    Dictionary keys can be either the service **component name** (not database name!)
    or `__default__`. The latter configuration is applied for every non-matching
    Mongo component of the service.
schema:
    type: object
    example: |
        {
            // Options for specified database.
            "mongo-stq_config": true,
            // Default options. Applied to all not specified components.
            // If __default__ section is not present,
            // use settings from MONGO_CONGESTION_CONTROL_ENABLED
            "__default__": false
        }
    properties:
        __default__:
            type: boolean
    additionalProperties:
        type: boolean
