openapi: 3.0.0
info:
    title: test-object client
    version: '1.0'

paths:
    /test1:
        get:
            parameters:
              - name: param1
                in: query
                required: true
                x-usrv-handler-tag: param1
                schema:
                    type: integer
              - name: param2
                in: query
                required: true
                x-usrv-handler-tag: param2
                schema:
                    type: number
              - name: param3
                in: query
                required: true
                x-usrv-handler-tag: param3
                schema:
                    type: string

              - name: param4
                in: query
                required: false
                x-usrv-handler-tag: param4
                schema:
                    type: integer
              - name: param5
                in: query
                required: false
                x-usrv-handler-tag: param5
                schema:
                    type: number
              - name: param6
                in: query
                required: false
                x-usrv-handler-tag: param6
                schema:
                    type: string

            responses:
                '200':
                    description: OK
components: {}
