swagger: '2.0'
description: test-object client

paths:
    /test1/PATH-123:
        post:
            parameters:
              - in: header
                name: X-Header-123
                type: string
              - $ref: '#/parameters/Parameter'
              # - $ref: '#/parameters/Body'
            responses:
                '200':
                    description: OK
                    # headers:
                    #     X-Header-123:
                    #         type: string
                    schema:
                        $ref: '#/definitions/Schema'
                '404':
                    $ref: '#/responses/Response404'

    /test1/no-tvm:
        post:
            x-usrv-middlewares:
                tvm: false
            responses:
                '200':
                    description: OK

    /test1/body:
        get:
            consumes:
              - application/json
            produces:
              - application/json
            parameters:
              - in: body
                name: body
                required: true
                schema:
                    type: string
            responses:
                '200':
                    description: OK


parameters:
    X-Header-456:
        in: header
        name: X-Header-456
        type: string
    Parameter:
        in: query
        name: some-header
        type: string
    Body:
        in: body
        name: body
        schema:
            type: object

responses:
    Response404:
        description: Not found
        schema:
            type: string

definitions:
    Schema:
        type: object
        additionalProperties: false
        properties: {}
